#application
server:
  port: 50800
  tomcat.max-threads: 20


#persistence
spring.datasource.url: jdbc:h2:mem:persondb
#spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres

spring.datasource.hikari.maximum-pool-size: "10"
spring.datasource.hikari.connection-timeout: "10000"

spring.sql.init.mode: always
spring.sql.init.schema-locations: classpath*:db/migration/V1__init.sql
spring.jpa.hibernate.ddl-auto: none

database.provisioning.goals: -import-demo-data


#logging
logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"
logging.level.org.goafabric.personservice.persistence.audit: "INFO"
